import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,copyFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {spawn} from 'node:child_process';
import {aggregationContract} from '../src/acceptance.js';
import {codexRuntime} from '../src/codex-runtime.js';

test('actual desktop main IPC completes chat, dispatch, checked delivery and legacy reads offline',{timeout:30000},async t=>{
 const root=await mkdtemp(join(tmpdir(),'legion-desktop-offline-')),project=join(root,'project'),catalog=join(root,'catalog');
 await mkdir(project);await mkdir(catalog);await mkdir(join(root,'.local/codex-runtime/node_modules/@openai/codex-win32-x64/vendor/x86_64-pc-windows-msvc/bin'),{recursive:true});
 await copyFile(process.execPath,codexRuntime(root));
 await writeFile(join(catalog,'models_cache.json'),JSON.stringify({models:[{slug:'gpt-6-sol',display_name:'GPT-6 Sol',visibility:'list',supported_reasoning_levels:[{effort:'medium'}]}]}));
 await writeFile(join(root,'account-capacity.json'),JSON.stringify([{backend:'codex',observedAt:new Date().toISOString(),available:false,concurrencyLimit:null}]));
 const goal='Aggregate numbers [3,1,2]: write aggregate.json with sum and sorted.',contract=aggregationContract(goal)!;
 const proposal={checks:contract.acceptance.map((criterion,i)=>({criterion,source:`import fs from 'node:fs';import assert from 'node:assert/strict';const value=JSON.parse(fs.readFileSync('aggregate.json','utf8'));${i===0?'assert.equal(value.sum,6);':'assert.deepEqual(value.sorted,[1,2,3]);'}`})),limitations:[]};
 const preload=join(root,'runtime-preload.cjs');
 await writeFile(preload,`const path=require('node:path');const Module=require('node:module');const original=Module._resolveFilename;const targets={"app-server":${JSON.stringify(join(root,'server.cjs'))},exec:${JSON.stringify(join(root,'worker.cjs'))}};Module._resolveFilename=function(request,...args){return targets[path.basename(request)]||original.call(this,request,...args);};`);
 await writeFile(join(root,'worker.cjs'),`const fs=require('node:fs');let text='';process.stdin.on('data',b=>text+=b);process.stdin.on('end',()=>{const i=process.argv.indexOf('--output-last-message');if(i>=0)fs.writeFileSync(process.argv[i+1],${JSON.stringify(JSON.stringify(proposal))});console.log(JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'Offline worker result'}}));console.log(JSON.stringify({type:'turn.completed',usage:{input_tokens:1,output_tokens:1}}));});`);
 await writeFile(join(root,'server.cjs'),`const fs=require('node:fs');const path=require('node:path');const rl=require('node:readline').createInterface({input:process.stdin});let nativeGoal;const send=x=>console.log(JSON.stringify(x));const tool=(id,name,args)=>send({id,method:'item/tool/call',params:{threadId:'fixture-thread',tool:name,arguments:args}});const finish=text=>{if(nativeGoal){nativeGoal={...nativeGoal,status:'complete'};send({method:'thread/goal/updated',params:{threadId:'fixture-thread',goal:nativeGoal}});}send({method:'item/completed',params:{threadId:'fixture-thread',item:{id:'final',type:'agentMessage',text}}});send({method:'turn/completed',params:{threadId:'fixture-thread',turn:{id:'fixture-turn',status:'completed'}}});};rl.on('line',line=>{const m=JSON.parse(line);if(m.method==='initialize')send({id:m.id,result:{}});if(m.method==='thread/start'){fs.writeFileSync('registered.json',JSON.stringify(m.params));send({id:m.id,result:{thread:{id:'fixture-thread'}}});}if(m.method==='thread/goal/get')send({id:m.id,result:{goal:nativeGoal}});if(m.method==='thread/goal/set'){nativeGoal={threadId:'fixture-thread',objective:'fixture',status:'paused',tokensUsed:0,timeUsedSeconds:0,createdAt:1,updatedAt:1,...nativeGoal,...m.params};send({id:m.id,result:{goal:nativeGoal}});}if(m.method==='thread/resume'){throw Error('Legacy specialized thread must not resume');}if(m.method==='turn/start'){fs.writeFileSync('last-turn.json',JSON.stringify(m.params));send({id:m.id,result:{turn:{id:'fixture-turn'}}});if(JSON.stringify(m.params).includes('Aggregate numbers'))tool('prepare','legion_delivery',${JSON.stringify({action:'prepare',contract})});else finish('Offline greeting');}if(m.method)return;if(m.result?.success===false){console.error(m.result);process.exit(1);}if(m.id==='prepare')tool('dispatch','legion_dispatch',{backend:'codex',prompt:'Return an offline fixture claim'});if(m.id==='dispatch'){const result=JSON.parse(m.result.contentItems[0].text);tool('wait','legion_tasks',{action:'wait',id:result.id,timeoutMs:5000});}if(m.id==='wait'){fs.writeFileSync('aggregate.json',JSON.stringify({sum:6,sorted:[1,2,3]}));tool('check','legion_delivery',{action:'check'});}if(m.id==='check'){fs.writeFileSync('delivery-tool-result.json',m.result.contentItems[0].text);finish('Offline delivery checked');}});`);
 const child=spawn(process.execPath,[resolve('tests/fixtures/desktop-host.cjs')],{cwd:process.cwd(),windowsHide:true,env:{...process.env,LEGION_CODE_ROOT:process.cwd(),LEGION_DATA_ROOT:root,LEGION_FIXTURE_PROJECT:project,CODEX_HOME:catalog,NODE_OPTIONS:`--require "${preload.replaceAll('\\','/')}"`},stdio:['ignore','pipe','pipe']});
 t.after(()=>{if(child.exitCode===null)child.kill();});
 let output='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>output+=b);
 const code=await new Promise<number|null>((resolve,reject)=>{child.once('error',reject);child.once('close',resolve);});assert.equal(code,0,output);
 const result=JSON.parse(await readFile(join(root,'offline-result.json'),'utf8'));assert.equal(result.status,'passed');assert.equal(result.realModelCalls,0);
});
