import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
const run=promisify(execFile);
async function command(root:string,action:string,id=''){const r=await run(process.execPath,['--import','tsx','tests/fixtures/resumable-process.ts',root,action,id],{maxBuffer:10_000_000});return JSON.parse(r.stdout.trim());}
test('real processes pause and resume same run, revalidate A and continue B and integration',async()=>{const root=await mkdtemp(join(tmpdir(),'engineering-resume-'));const {id}=await command(root,'create');const first=await command(root,'pause',id);assert.equal(first.status,'paused',JSON.stringify(first));assert.equal(first.team.tasks.a.status,'accepted');const second=await command(root,'resume',id);assert.equal(second.status,'completed',JSON.stringify(second));assert.equal(second.id,id);assert.equal(second.deadline,first.deadline);assert.equal(second.epoch,2);assert.equal(second.calls,first.calls+2);assert.equal(second.team.tasks.a.attempts.length,first.team.tasks.a.attempts.length);assert.ok(second.events.some((e:any)=>e.type==='revalidated:a'));const calls=(await readFile(join(root,'workers.jsonl'),'utf8')).trim().split('\n').map(s=>JSON.parse(s).id);assert.deepEqual(calls,['a','b','total']);});
import {writeFile,appendFile,mkdir} from 'node:fs/promises';import {createResumableEngineeringService} from '../src/engineering-run.js';import {claimRun} from '../src/engineering-store.js';import {frozenCheck} from '../src/engineering.js';
async function fixture(action='create'){const root=await mkdtemp(join(tmpdir(),'engineering-resume-'));const {id}=await command(root,action);return {root,id,dir:join(root,'.engineering',id)};}
async function paused(){const f=await fixture();await command(f.root,'pause',f.id);return f;}
test('crash at settled boundary recovers without rerunning A; completed resume is idempotent',async()=>{const f=await fixture();await assert.rejects(command(f.root,'crash',f.id));const r=await command(f.root,'resume',f.id);assert.equal(r.status,'completed');const again=await command(f.root,'resume',f.id);assert.equal(again.calls,r.calls);assert.equal(again.epoch,r.epoch);assert.equal((await readFile(join(f.root,'workers.jsonl'),'utf8')).trim().split('\n').length,3);});
test('concurrent resume has one owner and no duplicate dispatch',async()=>{const f=await fixture();const first=command(f.root,'hold',f.id);for(let n=0;n<100;n++){try{await readFile(join(f.root,'held'));break;}catch{await new Promise(r=>setTimeout(r,20));}}await assert.rejects(command(f.root,'resume',f.id),/still alive|EEXIST/);assert.equal((await first).status,'completed');});
test('surviving orphan worker and unknown checker block recovery',async()=>{for(const action of ['orphan','check-crash']){const f=await fixture();await assert.rejects(command(f.root,action,f.id));try{await assert.rejects(command(f.root,'resume',f.id),/outcome is unknown/);const state=await createResumableEngineeringService(f.root).detail(f.id);assert.ok(Object.keys(state.inflight).length>0);assert.ok(state.calls>=1);}finally{if(action==='orphan'){const {pid}=JSON.parse(await readFile(join(f.root,'orphan.json'),'utf8'));process.kill(pid);}}}});
test('cancel and original deadline prevent new dispatch',async()=>{const f=await paused();const service=createResumableEngineeringService(f.root);await service.cancel(f.id);await assert.rejects(command(f.root,'resume',f.id),/Cancelled/);const expired=await fixture('create-expired');await assert.rejects(command(expired.root,'resume',expired.id),/deadline expired/);});
test('cancel and resume racing before execution preserve the cancelled checkpoint',async()=>{const f=await fixture();const service=createResumableEngineeringService(f.root);const cancel=service.cancel(f.id),resume=service.resume(f.id);const rejected=assert.rejects(resume,/Cancelled/);await cancel;await rejected;assert.equal((await service.detail(f.id)).status,'cancelled');await assert.rejects(readFile(join(f.root,'workers.jsonl')),{code:'ENOENT'});});
test('cancel during engineering integration settlement cannot persist completed',async()=>{const f=await fixture();const state=await command(f.root,'cancel-settlement',f.id);assert.equal(state.status,'cancelled');assert.ok(state.delivery);assert.ok(!state.events.some((e:any)=>e.type==='delivery'));await assert.rejects(command(f.root,'resume',f.id),/Cancelled/);});
test('candidate, report, frozen challenge, dependency snapshot and source tampering block old PASS',async()=>{for(const kind of ['candidate','manifest','report','challenge','dependency','source']){const f=await paused();const s=await createResumableEngineeringService(f.root).detail(f.id);const e=s.nodes.a!;const target=kind==='candidate'?join(e.functional!.candidate.snapshot,'a.mjs'):kind==='manifest'?e.functional!.candidate.manifestPath:kind==='report'?e.functional!.acceptance.evidence!:kind==='challenge'?join(f.dir,'tasks','a','challenger','frozen-challenge.json'):kind==='dependency'?join(f.dir,'team','accepted','a','a.mjs'):join(f.root,'project','baseline.test.mjs');await appendFile(target,'\n// changed');const result=await command(f.root,'resume',f.id);assert.equal(result.status,'blocked',kind);assert.equal((await readFile(join(f.root,'workers.jsonl'),'utf8')).trim().split('\n').length,1,kind);}});
test('root integration fails although all nodes pass',async()=>{const f=await fixture('create-bad');const r=await command(f.root,'resume',f.id);assert.equal(r.status,'rejected');assert.ok(Object.values(r.team.tasks).every((t:any)=>t.status==='accepted'));});
test('partial log tail is not recovery authority and checkpoint write failure prevents dispatch',async()=>{const f=await paused();await appendFile(join(f.dir,'run-events.jsonl'),'{"half":');assert.equal((await command(f.root,'resume',f.id)).status,'completed');const bad=await paused();await mkdir(join(bad.dir,'run.tmp'));await command(bad.root,'resume',bad.id);assert.equal((await readFile(join(bad.root,'workers.jsonl'),'utf8')).trim().split('\n').length,1);});
test('late owner callbacks rejected and uncommitted state cannot claim accepted',async()=>{const root=await mkdtemp(join(tmpdir(),'owner-'));const lease=await claimRun(root,async()=>false);await writeFile(join(root,'owner.json'),JSON.stringify({pid:process.pid,token:'replacement'}));await assert.rejects(lease.assert(),/ownership changed/);});
test('secure checks reject zero tests and denied capabilities, scrub unrelated environment',async()=>{const root=await mkdtemp(join(tmpdir(),'node-check-'));await writeFile(join(root,'value.mjs'),'export const value=2');const plan={summary:'check',outputs:['value.mjs'],acceptance:['test'],limitations:[],testSource:''};const zero=await frozenCheck(root,join(root,'zero'),new AbortController().signal,{},plan,[],process.execPath,true);assert.notEqual(zero.checks[0]!.status,'pass');process.env.LEGION_TEST_SECRET='not-for-candidate';try{const safe=await frozenCheck(root,join(root,'safe'),new AbortController().signal,{}, {...plan,testSource:"import {test} from 'node:test';import assert from 'node:assert/strict';test('environment',()=>{assert.equal(process.env.LEGION_TEST_SECRET,undefined);assert.throws(()=>fetch('https://example.com'),/DENIED/);});"},[],process.execPath,true);assert.equal(safe.checks[0]!.status,'pass');}finally{delete process.env.LEGION_TEST_SECRET;}const invalid=await frozenCheck(root,join(root,'invalid'),new AbortController().signal,{}, {...plan,testSource:"import net from 'node:net';"},[],process.execPath,true);assert.notEqual(invalid.checks[0]!.status,'pass');});
import {createEngineeringProduct} from '../src/engineering-product.js';import {defaultChatOptions} from '../src/chat-options.js';
test('desktop service proposes checks without auto-dispatch, requires approval and lists original logical run',async()=>{const root=await mkdtemp(join(tmpdir(),'product-run-'));const project=join(root,'project');await mkdir(project);await writeFile(join(project,'baseline.test.mjs'),"import {test} from 'node:test';import assert from 'node:assert/strict';test('base',()=>assert.equal(2,2));");const plan={summary:'return two',outputs:['value.mjs'],acceptance:['value is two'],limitations:[],testSource:"import {test} from 'node:test';import assert from 'node:assert/strict';import {value} from './value.mjs';test('value',()=>assert.equal(value,2));"};let calls=0;const product=createEngineeringProduct(root,process.execPath,{planning:{plan:async()=>plan},execution:{run:async(_s,j)=>{calls++;await writeFile(join(j.workspace,'value.mjs'),'export const value=2');return {status:'completed',durationMs:0,text:'',usage:[],sessionId:'session-one'};},challenge:async c=>({checks:c.acceptance.map(criterion=>({criterion,source:"import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';const {value}=await import(pathToFileURL(process.cwd()+'/value.mjs'));assert.equal(value,2);"})),limitations:[]})}});const {id}=await product.plan({project,goal:'return two',options:{...defaultChatOptions,delegation:{mode:'auto',count:10}}});while(product.isActive())await new Promise(r=>setTimeout(r,20));const proposal=await product.detail(id);assert.equal(calls,0);assert.equal(proposal.status,'ready');await assert.rejects(product.approve(id,'wrong'),/approval/);await product.approve(id,(proposal as any).approvalHash);while(product.isActive())await new Promise(r=>setTimeout(r,20));const done=await product.detail(id);assert.equal(done.status,'completed',JSON.stringify(done));assert.equal(calls,1);assert.equal((await product.list()).filter(r=>r.id===id).length,1);assert.ok((await product.folder(id)).includes('snapshot'));});
import {spawn} from 'node:child_process';
test('killing real manager during a running Node verifier leaves unknown reservation and blocks replacement',async()=>{const f=await fixture('create-long');const child=spawn(process.execPath,['--import','tsx','tests/fixtures/resumable-process.ts',f.root,'resume',f.id],{stdio:'ignore',windowsHide:true});const closed=new Promise(r=>child.once('close',r));let verifier:number|undefined;try{const path=join(f.dir,'tasks','a','functional-1','checks','1','process.json');for(let i=0;i<300;i++){try{verifier=JSON.parse(await readFile(path,'utf8')).pid;break;}catch{await new Promise(r=>setTimeout(r,20));}}assert.ok(verifier,'real Node verifier started');child.kill();await closed;await assert.rejects(command(f.root,'resume',f.id),/outcome is unknown/);}finally{if(child.exitCode===null)child.kill();if(verifier)try{process.kill(verifier);}catch{}}});

test('exhausted cumulative call budget cannot dispatch B after pause/restart',async()=>{const f=await fixture('create-budget');const first=await command(f.root,'pause',f.id);assert.equal(first.status,'paused');assert.equal(first.calls,1);const result=await command(f.root,'resume',f.id);assert.equal(result.status,'blocked');assert.equal(result.calls,1);assert.equal((await readFile(join(f.root,'workers.jsonl'),'utf8')).trim().split('\n').length,1);});
