import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {managedChatWorker,validateManagementDecision} from '../src/managed-chat.js';
import type {ChatOptions} from '../src/chat-options.js';
const options:ChatOptions={model:'gpt-6-sol',effort:'medium',permission:'workspace-write',agents:0,delegation:{mode:'auto',count:10}};
const assignment=(id:string,backend:'codex'|'commandcode')=>({id,backend,goal:'Write a JSON artifact',outputs:[id+'.json'],acceptance:['JSON value equals 7']});
async function fixture(){const root=await mkdtemp(join(tmpdir(),'managed-goal-'));const workspace=join(root,'workspace'),attemptDir=join(root,'attempt');await mkdir(workspace);await mkdir(attemptDir);return {root,request:{workspace,attemptDir,prompt:'Implement the goal',timeoutMs:30000}};}
test('Manager chooses mixed workers then changes allocation using external evidence',async()=>{const {root,request}=await fixture();const backends:string[]=[];const worker=managedChatWorker(root,options,[],{challenge:async c=>({checks:[{criterion:c.acceptance[0],source:`import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';assert.equal(JSON.parse(readFileSync(${JSON.stringify(c.outputs[0])},'utf8')).value,7);`}],limitations:[]}),decide:async state=>{if(state.round===0)return {action:'delegate',reason:'Independent work',answer:'',tasks:[assignment('a','codex'),assignment('b','commandcode')]};assert.equal(state.tasks.length,2);assert.ok(state.tasks.every(t=>t.checks[0]?.sha256));return {action:'finish',reason:'Artifacts inspected',answer:'Delivered with limited checks',tasks:[]};},worker:async(spec,job)=>{backends.push(spec.backend);await mkdir(job.workspace,{recursive:true});const id=job.id.split('-').at(-1)!;await writeFile(join(job.workspace,id+'.json'),'{"value":7}');return {status:'completed',durationMs:1,text:'Done',usage:null};}});const r=await worker(request);assert.equal(r.status,'completed');assert.deepEqual(backends.sort(),['codex','commandcode'].sort());const state=JSON.parse(await readFile(join(request.attemptDir,'management.json'),'utf8'));assert.equal(state.decisions.length,2);assert.notEqual(state.tasks[0].workspace,state.tasks[1].workspace);});
test('auto can choose direct execution without spawning workers',async()=>{const {root,request}=await fixture();let calls=0;const r=await managedChatWorker(root,options,[],{decide:async()=>({action:'work',reason:'Too small to split',answer:'',tasks:[]}),worker:async spec=>{calls++;assert.equal(spec.backend,'codex');return {status:'completed',text:'Direct answer',usage:null,durationMs:1};}})(request);assert.equal(calls,1);assert.equal(r.status,'completed');});
test('modes enforce off and fixed limits and reject unsafe output paths',()=>{const raw={action:'delegate',reason:'split',answer:'',tasks:[assignment('a','codex')]};assert.throws(()=>validateManagementDecision(raw,{...options,delegation:{mode:'off',count:10}},0));assert.throws(()=>validateManagementDecision({...raw,tasks:[assignment('a','codex'),assignment('b','codex')]},{...options,delegation:{mode:'fixed',count:1}},0));assert.throws(()=>validateManagementDecision({...raw,tasks:[{...assignment('a','codex'),outputs:['../x']}]},options,0));assert.equal(validateManagementDecision({action:'finish',tasks:[],reason:'Greeting needs no delegation',answer:'你好'},{...options,delegation:{mode:'fixed',count:10}},0).action,'finish');});
test('worker self report cannot conceal failed external artifact check',async()=>{const {root,request}=await fixture();const r=await managedChatWorker(root,options,[],{decide:async state=>state.round===0?{action:'delegate',reason:'work',answer:'',tasks:[assignment('a','commandcode')]}:{action:'finish',reason:'stop',answer:'Not complete',tasks:[]},worker:async(_spec,job)=>{await mkdir(job.workspace,{recursive:true});await writeFile(join(job.workspace,'a.json'),'invalid');return {status:'completed',durationMs:1,text:'Everything is perfect',usage:null};}})(request);assert.equal(r.status,'completed');assert.notEqual(r.acceptance?.status,'accepted');const state=JSON.parse(await readFile(join(request.attemptDir,'management.json'),'utf8'));assert.equal(state.tasks[0].status,'checks_failed');});

test('Command Code file adapter denies outside paths, links and unlisted tools',async()=>{
 const {pathToFileURL}=await import('node:url');const {symlink}=await import('node:fs/promises');
 const {guardTool}=await import(pathToFileURL(join(process.cwd(),'scripts/capacity/workspace-mod.mjs')).href);
 const {root,request}=await fixture();assert.equal(await guardTool(request.workspace,{toolName:'write_file',input:{file_path:join(request.workspace,'ok.json')}}),undefined);
 assert.equal((await guardTool(request.workspace,{toolName:'write_file',input:{file_path:join(root,'outside.json')}})).block,true);
 assert.equal((await guardTool(request.workspace,{toolName:'run_command',input:{command:'anything'}})).block,true);
 assert.equal((await guardTool(request.workspace,{toolName:'agent',input:{}})).block,true);
 const external=join(root,'external');await mkdir(external);await symlink(external,join(request.workspace,'link'),'junction');assert.equal((await guardTool(request.workspace,{toolName:'write_file',input:{file_path:join(request.workspace,'link','x')}})).block,true);
});

test('fixed mode can answer a greeting without any worker or tests',async()=>{const {root,request}=await fixture();const result=await managedChatWorker(root,{...options,delegation:{mode:'fixed',count:10}},[],{decide:async()=>({action:'finish',reason:'Conversation only',answer:'你好，有什么需要帮助的？',tasks:[]}),worker:async()=>{throw Error('Greeting must not spawn');}})({...request,prompt:'hi'});assert.equal(result.status,'completed');assert.match(await readFile(join(request.attemptDir,'stdout.jsonl'),'utf8'),/你好/);});
