import {createGoalService} from './persistent-goal.js';
import {readFile} from 'node:fs/promises';import {join} from 'node:path';
import {createEngineeringService,projectFiles} from './engineering.js';import {createResumableEngineeringService,approvalHash} from './engineering-run.js';
/** Desktop facade: legacy records are history, new plans require explicit check approval. */
export function createEngineeringProduct(root:string,node=process.execPath,deps:{planning?:Parameters<typeof createEngineeringService>[2];execution?:Parameters<typeof createResumableEngineeringService>[2]}={}){
 const goals=createGoalService(root);
 const legacy=createEngineeringService(root,node,deps.planning),runs=createResumableEngineeringService(root,node,deps.execution);
 const isActive=()=>legacy.isActive()||runs.isActive()||goals.isActive();
 const has=async(id:string)=>{if(!/^[a-f0-9-]{36}$/.test(id))throw Error('Invalid Run ID');try{await readFile(join(root,'.engineering',id,'run.json'));return true;}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return false;throw e;}};
 async function detail(id:string){if(await goals.has(id))return goals.detail(id);if(await has(id))return {...await runs.detail(id),resumable:true};const r=await legacy.detail(id);if(!r.resumableRequested)return {...r,historyOnly:true};return {...r,approvalHash:r.plan?approvalHash(r.goal,await projectFiles(r.project),r.plan):undefined};}
 async function approve(id:string,hash:string){if(isActive())throw Error('请先暂停当前执行');const r=await legacy.detail(id);if(!r.resumableRequested||r.status!=='ready'||!r.plan)throw Error('该记录仅能查看历史');const original=JSON.parse(await readFile(join(root,'.engineering',id,'state.json'),'utf8'));if(approvalHash(r.goal,await projectFiles(r.project),r.plan)!==approvalHash(r.goal,original.files,r.plan))throw Error('项目已变化，请重新规划');let usage:unknown[]=[];try{usage=[{role:'manager-planner',events:await readFile(join(root,'.engineering',id,'planner','stdout.jsonl'),'utf8')}];}catch{/* Fixture planner has no model usage. */}
 await runs.create({id,project:r.project,goal:r.goal,plan:r.plan,options:r.options,workerOptions:r.workerOptions,approvedHash:hash,initialCalls:r.planningBudget?.calls??1,initialUsage:usage,absoluteDeadline:r.planningBudget?.deadline});return runs.resume(id);}
 return {isActive,detail,approve,startGoal:async(input:Parameters<typeof goals.create>[0])=>{if(isActive())throw Error('请先暂停当前执行');const created=await goals.create(input);return goals.resume(created.id);},support:async(project:string)=>{let files:Record<string,string>;try{files=await projectFiles(project);}catch(error){return {supported:false,reason:'当前可恢复任务无法为此项目建立验证快照：'+String(error)};}const supported=Object.keys(files).some(f=>/\.(test|spec)\.(mjs|cjs|js)$/.test(f));return {supported,reason:supported?'':'当前可恢复任务的验证器不支持此项目（未找到 Node 行为测试）'};},plan:(input:Parameters<typeof legacy.plan>[0])=>{if(isActive())throw Error('请先暂停当前执行');return legacy.plan({...input,resumable:true});},list:async()=>{const newer=await runs.list(),ids=new Set(newer.map(r=>r.id));return [...await goals.list(),...newer,...(await legacy.list()).filter(r=>!ids.has(r.id))];},start:()=>{throw Error('请审核检查覆盖并批准后执行');},resume:async(id:string)=>{if(await goals.has(id)){if(legacy.isActive()||runs.isActive())throw Error('请先暂停当前执行');return goals.resume(id);}if(goals.isActive())throw Error('请先暂停持续目标');if(legacy.isActive())throw Error('规划仍在执行');return runs.resume(id);},pause:()=>goals.isActive()?goals.pause():runs.pause(),cancel:async(id:string)=>await goals.has(id)?goals.cancel(id):runs.cancel(id),stop:async()=>{await goals.pause();await legacy.stop();await runs.pause();},folder:async(id:string)=>{if(await goals.has(id))return goals.folder(id);if(!await has(id))return legacy.folder(id);const r=await runs.detail(id);if(r.status!=='completed'||!r.delivery)throw Error('尚无验收通过的交付');return r.delivery.candidate.snapshot;}};
}
