const $ = id => document.getElementById(id);
const token = document.querySelector('meta[name="ui-token"]').content;
let preset = 'demo', selected = null, busy = false, currentLaunch = null;
const labels = { unconfirmed:'状态待确认', pending:'等待依赖', running:'执行中', checking:'检查中', deciding:'Master 决策中', accepted:'已验收', completed:'已完成', incomplete:'未全部完成', failed:'未通过', unverified:'证据不足', error:'运行异常', blocked:'上游阻塞', cancelled:'已停止', timeout:'已超时', pass:'通过', fail:'失败', not_checked:'未检查', resume:'继续修复', switch:'切换路线', verify:'补充验证', accept:'验收交付', stop:'停止' };
const label = s => labels[s] || s;
const escape = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = s => s ? new Date(s).toLocaleString('zh-CN', {month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}) : '';
const badge = s => `<span class="badge ${['accepted','completed','pass'].includes(s)?'good':['error','failed','fail','incomplete','timeout'].includes(s)?'bad':''}">${escape(label(s))}</span>`;
async function api(path, data) { const response = await fetch(path, {method:data?'POST':'GET',headers:{'X-UI-Token':token,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined}); const value=await response.json(); if(!response.ok)throw Error(value.error); return value; }
document.querySelectorAll('.preset').forEach(button => button.onclick = () => { preset=button.dataset.preset; document.querySelectorAll('.preset').forEach(b=>b.classList.toggle('selected',b===button)); $('cost-row').hidden=preset==='demo'; $('cost').checked=false; $('start').textContent=preset==='demo'?'启动演示 →':'启动真实任务 →'; $('description').textContent=preset==='demo'?'这是流程演示，不代表真实工程任务的能力或成功率。':'真实示例：两个独立任务各输出 42，通过验收后交给第三个任务汇总为 84。'; });
$('start').onclick=async()=>{if(busy)return;busy=true;$('start').disabled=true;$('message').textContent='正在启动…';try{const launch=await api('/api/start',{preset,confirmCost:$('cost').checked});currentLaunch=launch.id;$('message').textContent='任务已启动，运行记录即将出现。';await refresh();}catch(e){$('message').textContent=e.message;}finally{busy=false;}};
$('stop').onclick=async()=>{try{const result=await api('/api/stop',{});$('message').textContent=result.message;}catch(e){$('message').textContent=e.message;}};
async function detail(){if(!selected)return;const data=await api('/api/run?id='+encodeURIComponent(selected));const state=data.state;const entries=Object.entries(state.tasks||{});$('run-title').textContent=selected.startsWith('team-demo-')?'协作流程演示':'真实任务运行';$('run-status').outerHTML=`<span id="run-status" class="badge">${escape(label(state.status))}</span>`;$('run-meta').textContent=`${date(state.startedAt)} · ${data.provenance.policy==='codex-master-v1'?'LLM Master':selected.startsWith('team-demo-')?'模拟 worker · 规则策略':'规则策略'} · ${selected.slice(-8)}`;const accepted=entries.filter(([,t])=>t.status==='accepted').length;
  const track=document.createElement('progress');track.max=Math.max(1,entries.length);track.value=accepted;track.className='track';$('progress').replaceChildren(track,document.createTextNode(`${accepted} / ${entries.length} 个任务通过验收`));
  $('tasks').innerHTML=entries.map(([id,t])=>`<article class="task"><div class="task-title"><strong>${escape(id)}</strong>${badge(t.status)}</div><p>尝试 ${t.attempts.length} 次 · 路线 ${t.route+1}</p><p>${escape(state.config.tasks.find(x=>x.id===id)?.dependsOn.join('、')||'独立任务')} ${state.config.tasks.find(x=>x.id===id)?.dependsOn.length?'→ 本任务':''}</p>${t.reason?`<p>${escape(t.reason)}</p>`:''}</article>`).join('');
  const events=data.events.filter(e=>['worker_started','master_decision','task_finished','team_finished'].includes(e.type)).reverse();$('timeline').innerHTML=events.map(e=>`<div class="event"><time>${date(e.at)}</time><strong>${escape(e.data.task||'管理器')} · ${escape(e.type==='master_decision'?label(e.data.decision.action):e.type==='worker_started'?'开始执行':e.type==='team_finished'?'运行结束':label(e.data.status))}</strong>${e.data.decision?`<p>${escape(e.data.decision.reason)}</p>${e.data.decision.guidance?`<p>建议：${escape(e.data.decision.guidance)}</p>`:''}`:''}</div>`).join('')||'<p class="empty">等待第一条执行事件…</p>';
  $('evidence').innerHTML=entries.map(([id,t])=>{const a=t.attempts.at(-1);const report=a?.verification||a?.report;return `<h3>${escape(id)}</h3>${(report?.checks||[]).map(c=>`<div class="evidence-item">${escape(c.id)} ${badge(c.status)}<p>${escape(c.detail)}</p></div>`).join('')}${t.artifacts.map(a=>`<div class="evidence-item">▤ ${escape(a.path)}<p>SHA256 ${escape(a.sha256.slice(0,16))}…</p></div>`).join('')}${!report?'<p class="empty">等待检查结果</p>':''}`;}).join('');$('report').textContent=data.report||'运行尚未生成最终报告。';}
async function refresh(){try{const data=await api('/api/runs');$('start').disabled=Boolean(data.active)||busy;$('stop').hidden=!data.active;const launch=data.launches.find(l=>l.id===currentLaunch);if(launch?.runId&&selected!==launch.runId){selected=launch.runId;currentLaunch=null;}if(launch?.status==='error'){$('message').textContent=launch.detail||'启动失败';currentLaunch=null;}const latest=data.launches[0];if(latest&&['cancelled','timeout'].includes(latest.status))$('message').textContent='执行进程已停止。记录保留最后检查点；未完成的任务不能视为已验收。';if(!selected&&data.runs.length)selected=data.runs[0].id;$('count').textContent=data.runs.length;$('history-list').innerHTML=data.runs.map(r=>`<button class="history-item ${r.id===selected?'selected':''}" data-run="${escape(r.id)}"><div class="row"><strong>${r.demo?'流程演示':'真实任务'}</strong>${badge(r.status)}</div><small>${date(r.startedAt)}</small><small>${r.accepted}/${r.total} 已验收 · ${escape(r.id.slice(-8))}</small></button>`).join('')||'<p class="empty">还没有运行记录。<br>点击上方「启动演示」。</p>';document.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>{selected=b.dataset.run;void refresh();});await detail();}catch(e){$('message').textContent='连接异常：'+e.message;}}
void refresh();setInterval(()=>{void refresh();},1800);
